name: wildfire
description: A fast communication chat application developed using Google Firebase.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - src/icon.png
